# Elasticsearch configuration for Claude Code Dev Environment

cluster.name: claude-cluster
node.name: claude-node-1

# Paths
path.data: /usr/share/elasticsearch/data
path.logs: /usr/share/elasticsearch/logs

# Network
network.host: 0.0.0.0
http.port: 9200

# Discovery
discovery.type: single-node

# Security (disabled for development)
xpack.security.enabled: false
xpack.security.enrollment.enabled: false

# Monitoring
xpack.monitoring.collection.enabled: true

# Memory
bootstrap.memory_lock: true

# CORS (for development)
http.cors.enabled: true
http.cors.allow-origin: "*"
http.cors.allow-methods: OPTIONS, HEAD, GET, POST, PUT, DELETE
http.cors.allow-headers: "X-Requested-With, Content-Type, Content-Length, X-User"

# Performance
indices.memory.index_buffer_size: 30%
indices.queries.cache.size: 15%
indices.fielddata.cache.size: 25%

# Thread pools
thread_pool.search.size: 20
thread_pool.search.queue_size: 10000
thread_pool.write.size: 10
thread_pool.write.queue_size: 10000

# Circuit breakers
indices.breaker.total.limit: 85%
indices.breaker.fielddata.limit: 60%
indices.breaker.request.limit: 60%

# Logging
logger.level: INFO
logger.action.level: DEBUG