# Frontend Team Configuration
# Team-specific settings for frontend developers using Claude Code + SuperClaude + MCP

metadata:
  team: "frontend-team"
  version: "1.0.0"
  last_updated: "2024-01-15T10:00:00Z"
  maintainer: "frontend-team-lead"
  description: "Frontend team configuration focused on UI/UX development, accessibility, and modern web frameworks"

# Team information
team_info:
  name: "Frontend Development Team"
  lead: "sarah.johnson@company.com"
  slack_channel: "#frontend-team"
  meeting_schedule: "Daily standup at 9:00 AM, Sprint planning every 2 weeks"
  focus_areas:
    - "React/Vue/Angular development"
    - "Responsive design and mobile-first development"
    - "Web accessibility (WCAG compliance)"
    - "Performance optimization"
    - "Design system implementation"
    - "Progressive Web Apps (PWA)"

# Claude configuration overrides for frontend team
claude:
  # Frontend-optimized model settings
  model:
    temperature: 0.2  # Slightly higher for creative UI solutions
    
  # Frontend-specific features
  features:
    ui_generation: true
    accessibility_checking: true
    responsive_design_tools: true
    performance_profiling: true
    
  # Frontend development focus
  development_focus:
    primary_technologies:
      - "React"
      - "TypeScript"
      - "CSS/SCSS"
      - "JavaScript ES6+"
      - "HTML5"
      - "Web APIs"
    
    frameworks:
      - "Next.js"
      - "Vue.js"
      - "Angular"
      - "Svelte"
    
    tools:
      - "Webpack"
      - "Vite"
      - "ESLint"
      - "Prettier"
      - "Jest"
      - "Cypress"

# SuperClaude frontend-specific configuration
superclaude:
  # Persona preferences for frontend team
  personas:
    primary: "frontend"
    auto_activation_keywords:
      - "component"
      - "UI"
      - "UX"
      - "responsive"
      - "accessibility"
      - "CSS"
      - "JavaScript"
      - "React"
      - "Vue"
      - "Angular"
    
    # Team-specific persona customizations
    frontend_persona:
      priority_hierarchy: "User experience > accessibility > performance > technical elegance"
      focus_areas:
        - "Modern CSS (Grid, Flexbox, Custom Properties)"
        - "Component architecture and design patterns"
        - "State management (Redux, Vuex, NgRx)"
        - "Testing strategies (Unit, Integration, E2E)"
        - "Build optimization and bundle analysis"
      
      performance_budgets:
        load_time_3g: "3s"
        load_time_wifi: "1s"
        bundle_size_initial: "500KB"
        bundle_size_total: "2MB"
        accessibility_score: "90%"
        core_web_vitals:
          lcp: "2.5s"
          fid: "100ms"
          cls: "0.1"
    
    # Secondary personas for frontend team
    secondary_personas:
      - "performance"  # For optimization tasks
      - "qa"          # For testing and quality assurance
      - "architect"   # For system design decisions

  # Frontend-specific commands and workflows
  commands:
    preferred_commands:
      - "/build --frontend"
      - "/implement --type component"
      - "/improve --focus accessibility"
      - "/test --type e2e"
      - "/analyze --focus performance"
    
    custom_aliases:
      "/ui": "/implement --type component --framework react"
      "/responsive": "/improve --focus responsive-design"
      "/a11y": "/improve --focus accessibility"
      "/perf": "/analyze --focus performance"

  # Flag preferences
  flags:
    default_flags:
      - "--persona-frontend"
      - "--magic"
      - "--c7"
    
    auto_flags:
      ui_tasks: "--magic --persona-frontend"
      performance_tasks: "--persona-performance --play"
      testing_tasks: "--persona-qa --play"

# MCP server preferences for frontend team
mcp:
  # Preferred MCP servers for frontend development
  preferred_servers:
    - "magic"      # UI component generation (primary)
    - "context7"   # Framework documentation
    - "playwright" # E2E testing and browser automation
    - "sequential" # Complex problem solving
  
  # Server-specific configurations
  server_configs:
    magic:
      priority: "high"
      features:
        component_generation: true
        design_system_integration: true
        accessibility_compliance: true
        responsive_design: true
      
      frameworks:
        - "React"
        - "Vue"
        - "Angular"
        - "Web Components"
      
      component_preferences:
        default_framework: "React"
        typescript_preferred: true
        css_approach: "CSS Modules"
        accessibility_by_default: true
    
    context7:
      priority: "high"
      focus_libraries:
        - "react"
        - "vue"
        - "angular"
        - "typescript"
        - "css"
        - "html"
        - "javascript"
        - "webpack"
        - "vite"
    
    playwright:
      priority: "medium"
      use_cases:
        - "E2E testing"
        - "Cross-browser testing"
        - "Visual regression testing"
        - "Performance monitoring"
        - "Accessibility testing"

# Development workflow preferences
workflows:
  # Git workflow preferences
  git:
    branch_naming: "feature/frontend-{feature-name}"
    commit_conventions: "conventional-commits"
    required_checks:
      - "lint"
      - "type-check"
      - "unit-tests"
      - "build"
      - "accessibility-audit"
    
    pre_commit_hooks:
      - "eslint"
      - "prettier"
      - "stylelint"
      - "accessibility-check"
  
  # Code review process
  code_review:
    required_reviewers: 2
    required_approvals: 1
    auto_request_reviews: true
    review_checklist:
      - "Accessibility compliance verified"
      - "Responsive design tested"
      - "Performance impact assessed"
      - "Browser compatibility checked"
      - "Unit tests added/updated"
      - "Documentation updated"
  
  # Testing strategy
  testing:
    unit_tests:
      framework: "Jest"
      coverage_threshold: 80
      required_for_components: true
    
    integration_tests:
      framework: "Testing Library"
      focus_areas:
        - "User interactions"
        - "API integration"
        - "State management"
    
    e2e_tests:
      framework: "Playwright"
      browsers: ["chrome", "firefox", "safari"]
      viewports: ["mobile", "tablet", "desktop"]
    
    accessibility_tests:
      automated: "axe-core"
      manual_checklist: true
      wcag_level: "AA"

# Quality standards and guidelines
quality_standards:
  # Code quality
  code_quality:
    eslint_config: "@company/eslint-config-frontend"
    prettier_config: "@company/prettier-config"
    stylelint_config: "@company/stylelint-config"
    
    complexity_limits:
      cyclomatic_complexity: 10
      cognitive_complexity: 15
      function_length: 50
      file_length: 300
  
  # Performance standards
  performance:
    lighthouse_score_threshold: 85
    bundle_size_budget:
      initial: "500KB"
      total: "2MB"
      per_route: "200KB"
    
    core_web_vitals:
      lcp_threshold: "2.5s"
      fid_threshold: "100ms"
      cls_threshold: "0.1"
  
  # Accessibility standards
  accessibility:
    wcag_compliance: "AA"
    automated_testing: true
    manual_testing_required: true
    screen_reader_testing: true
    
    requirements:
      - "Semantic HTML structure"
      - "Proper ARIA labels and roles"
      - "Keyboard navigation support"
      - "Color contrast compliance"
      - "Focus management"
      - "Screen reader compatibility"

# Tool configurations
tools:
  # Package managers
  package_manager: "npm"  # or "yarn", "pnpm"
  
  # Build tools
  build_tool: "vite"  # or "webpack", "rollup"
  
  # CSS processing
  css_processor: "sass"
  css_framework: "tailwind"  # or "bootstrap", "bulma", custom
  
  # State management
  state_management:
    react: "redux-toolkit"
    vue: "pinia"
    angular: "ngrx"
  
  # Testing tools
  testing_tools:
    unit: "jest"
    integration: "@testing-library/react"
    e2e: "playwright"
    visual: "chromatic"
  
  # Development tools
  dev_tools:
    linter: "eslint"
    formatter: "prettier"
    type_checker: "typescript"
    bundler_analyzer: "webpack-bundle-analyzer"

# Environment-specific settings
environment_overrides:
  development:
    debugging:
      react_devtools: true
      vue_devtools: true
      redux_devtools: true
    
    hot_reload: true
    source_maps: true
    
  staging:
    performance_monitoring: true
    error_tracking: true
    
  production:
    minification: true
    tree_shaking: true
    code_splitting: true
    asset_optimization: true

# Learning and development
learning_resources:
  documentation:
    - "MDN Web Docs"
    - "React Documentation"
    - "Vue.js Guide"
    - "Angular Documentation"
    - "Web Accessibility Guidelines"
  
  training_programs:
    - "Modern JavaScript/TypeScript"
    - "Advanced React Patterns"
    - "Web Performance Optimization"
    - "Accessibility Best Practices"
    - "Design Systems"
  
  conferences:
    - "React Conf"
    - "Vue.js Conference"
    - "Frontend Masters"
    - "A11y Conference"

# Notification preferences
notifications:
  channels:
    primary: "slack"
    secondary: "email"
  
  events:
    build_failures: true
    deployment_success: true
    performance_regressions: true
    accessibility_violations: true
    dependency_updates: false  # Too noisy for frontend
  
  quiet_hours:
    enabled: true
    start: "19:00"
    end: "09:00"
    timezone: "America/New_York"

# Metrics and KPIs
metrics:
  # Development metrics
  development:
    - "Feature delivery velocity"
    - "Bug resolution time"
    - "Code review turnaround"
    - "Test coverage percentage"
    - "Build success rate"
  
  # Quality metrics
  quality:
    - "Lighthouse performance score"
    - "Accessibility compliance rate"
    - "Cross-browser compatibility"
    - "User experience metrics"
    - "Core Web Vitals"
  
  # Team metrics
  team:
    - "Team satisfaction score"
    - "Knowledge sharing frequency"
    - "Training completion rate"
    - "Tool adoption rate"