# Development Environment Configuration
# Claude Code + SuperClaude + MCP Development Environment

metadata:
  environment: development
  version: "1.0.0"
  last_updated: "2024-01-15T10:00:00Z"
  maintainer: "devops-team"
  description: "Development environment for Claude Code with full debugging and development features"

# Core Claude configuration
claude:
  environment_type: development
  debug_mode: true
  verbose_logging: true
  telemetry_enabled: true
  
  # Model settings for development
  model:
    primary: "claude-3-5-sonnet-20241022"
    fallback: "claude-3-haiku-20240307"
    max_tokens: 8192
    temperature: 0.1
    
  # Development-specific features
  features:
    experimental_features: true
    beta_access: true
    development_tools: true
    hot_reload: true
    auto_save: true
    
  # Performance settings (relaxed for development)
  performance:
    request_timeout: 60
    max_concurrent_requests: 10
    cache_enabled: true
    cache_ttl: 300
    
  # Error handling
  error_handling:
    detailed_errors: true
    stack_traces: true
    error_reporting: true
    retry_attempts: 3
    retry_delay: 1000

# SuperClaude framework configuration
superclaude:
  enabled: true
  version: "3.1.0"
  
  # Framework features
  features:
    wave_orchestration: true
    sub_agent_delegation: true
    task_management: true
    introspection_mode: true
    token_efficiency: true
    
  # Development-specific settings
  development:
    verbose_output: true
    debug_personas: true
    trace_decision_making: true
    performance_metrics: true
    
  # Persona configuration
  personas:
    auto_activation: true
    custom_personas_allowed: true
    persona_debugging: true
    
  # Command system
  commands:
    custom_commands_enabled: true
    command_validation: "relaxed"
    command_logging: true
    
  # Flag system
  flags:
    auto_flag_detection: true
    flag_conflicts_warnings: true
    experimental_flags: true

# MCP (Model Context Protocol) configuration
mcp:
  enabled: true
  auto_discovery: true
  health_checks: true
  performance_monitoring: true
  
  # Connection settings
  connection:
    timeout: 30
    max_retries: 3
    retry_delay: 2000
    keep_alive: true
    
  # Development features
  development:
    server_debugging: true
    protocol_logging: true
    performance_profiling: true
    mock_servers_enabled: true

# Security configuration (development - relaxed)
security:
  authentication:
    required: false  # Relaxed for development
    method: "api_key"
    timeout: 3600
    
  authorization:
    rbac_enabled: false  # Simplified for development
    default_permissions: "full"
    
  data_protection:
    encryption_at_rest: false  # Optional for development
    encryption_in_transit: true
    data_retention_days: 30
    
  audit:
    enabled: true
    detailed_logging: true
    
  network:
    allowed_hosts: ["*"]  # Open for development
    cors_enabled: true
    rate_limiting: false

# Monitoring and observability
monitoring:
  enabled: true
  
  # Metrics collection
  metrics:
    prometheus_enabled: true
    custom_metrics: true
    performance_metrics: true
    
  # Logging
  logging:
    level: "debug"
    structured_logging: true
    log_rotation: true
    log_retention_days: 7
    
  # Tracing
  tracing:
    enabled: true
    sampling_rate: 1.0  # 100% sampling for development
    jaeger_enabled: true
    
  # Health checks
  health_checks:
    enabled: true
    interval: 30
    timeout: 10
    endpoints:
      - "/health"
      - "/ready"
      - "/metrics"

# Development tools integration
development_tools:
  # Hot reload configuration
  hot_reload:
    enabled: true
    watch_paths:
      - "src/**/*"
      - "config/**/*"
      - ".claude/**/*"
    ignore_patterns:
      - "node_modules/**"
      - ".git/**"
      - "logs/**"
      
  # Auto-save configuration
  auto_save:
    enabled: true
    interval: 30
    backup_count: 10
    
  # Debugging tools
  debugging:
    breakpoints_enabled: true
    step_debugging: true
    variable_inspection: true
    performance_profiling: true
    
  # Testing integration
  testing:
    unit_tests_auto_run: true
    integration_tests_on_sync: true
    test_coverage_reporting: true

# Database configuration (development)
database:
  # PostgreSQL for development
  postgres:
    host: "localhost"
    port: 5432
    database: "claude_dev"
    username: "claude_dev"
    # Password managed via environment variable
    connection_pool:
      min_connections: 2
      max_connections: 10
      
  # Redis for caching and sessions
  redis:
    host: "localhost"
    port: 6379
    database: 0
    password: null  # No password for development
    
  # MongoDB for document storage
  mongodb:
    host: "localhost"
    port: 27017
    database: "claude_dev"
    username: "claude_dev"
    # Password managed via environment variable

# File system configuration
filesystem:
  # Claude directory
  claude_dir: "${HOME}/.claude"
  
  # Workspace configuration
  workspace:
    root: "${HOME}/workspace"
    projects_dir: "${HOME}/workspace/projects"
    temp_dir: "/tmp/claude-dev"
    
  # Backup configuration
  backups:
    enabled: true
    directory: "${HOME}/.claude/backups"
    retention_days: 30
    auto_cleanup: true
    
  # Cache configuration
  cache:
    enabled: true
    directory: "${HOME}/.claude/cache"
    max_size_mb: 1024
    ttl_hours: 24

# Network configuration
network:
  # API endpoints
  api:
    base_url: "http://localhost:8080"
    timeout: 30
    retries: 3
    
  # WebSocket configuration
  websocket:
    enabled: true
    port: 8081
    ping_interval: 30
    
  # Proxy configuration (for development behind corporate firewall)
  proxy:
    enabled: false
    http_proxy: null
    https_proxy: null
    no_proxy: "localhost,127.0.0.1"

# Feature flags (development)
feature_flags:
  # Experimental features
  experimental_ui: true
  advanced_debugging: true
  beta_mcp_servers: true
  enhanced_personas: true
  
  # Development features
  mock_data_enabled: true
  test_mode_available: true
  debug_panels: true
  performance_monitoring: true
  
  # Integration features
  git_integration: true
  ci_cd_integration: true
  slack_notifications: false  # Disabled for development noise
  email_notifications: false

# Validation rules
validation:
  # Configuration validation
  config_validation:
    strict_mode: false  # Relaxed for development
    schema_validation: true
    custom_validators: true
    
  # Runtime validation
  runtime_validation:
    enabled: true
    performance_impact_allowed: true
    detailed_error_messages: true

# Environment-specific overrides
overrides:
  # Allow environment-specific customizations
  allow_user_overrides: true
  allow_project_overrides: true
  allow_team_overrides: true
  
  # Override precedence (highest to lowest)
  precedence:
    - user_local
    - project_specific
    - team_specific
    - environment_default
    - base_configuration

# Resource limits (generous for development)
resources:
  memory:
    max_heap_size: "2g"
    max_cache_size: "512m"
    
  cpu:
    max_threads: 8
    thread_pool_size: 4
    
  disk:
    max_log_size: "100m"
    max_cache_size: "1g"
    max_backup_size: "500m"

# Development environment metadata
environment_info:
  purpose: "Development and testing of Claude Code features"
  stability: "experimental"
  data_classification: "development"
  backup_criticality: "low"
  monitoring_level: "verbose"
  support_level: "best-effort"